# Copyright (C) 2022 Shra1V32 <namanageshwar@outlook.com>
name: Tata Sky Daily Workflow
on:
 schedule:
   - cron: "00 21  * * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Daily Loop
      run: |
            git config --global user.name "$git_id"
            git config --global user.email "$git_mail"
            git clone https://$git_token@github.com/$git_id/TataSkyIPTV-Daily
            cd TataSkyIPTV-Daily/
            cd code_samples/
            curl -s 'https://raw.githubusercontent.com/Shra1V32/TataSky-Playlist-AutoUpdater/main/dependencies/post_script.exp' > script.exp &
            curl -s 'https://gist.githubusercontent.com/Shra1V32/ee918d53b2f0b65888809ba85f0e0183/raw/allChannels.json' > allChannels.json
            chmod 755 *
            sudo apt install expect -y
            ./script.exp
            git clone ${gist_url}
            rm ${dir}/allChannelPlaylist.m3u
            mv *.m3u ${dir}/
            cd ${dir}
            git add .
            git commit --amend -m "Playlist has been updated."
            git push -f
